tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "bash-completion"
brew "git"
brew "imagemagick"
brew "jq"
brew "kustomize"
brew "nvm"
brew "stern"
brew "tig"
brew "tree"
brew "wget"

cask "font-hackgen"
